### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by yarikoptic** [mih/datalad-mihextras#41]
datalad-extensions have been failing testing this extension for a while due to datalad dropping `nose` and migration to pytest in this extension were done only after last release 0.7.0

```
======================================================================
ERROR: test suite for <module 'datalad_mihextras' from '/opt/hostedtoolcache/Python/3.7.[17](https://github.com/datalad/datalad-extensions/actions/runs/6104815637/job/16567389712#step:10:18)/x64/lib/python3.7/site-packages/datalad_mihextras/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/datalad/__init__.py", line 141, in setup_package
    from datalad.tests.utils import setup_package
ModuleNotFoundError: No module named 'datalad.tests.utils'
-------------------- >> begin captured logging << --------------------
```

**Comment by mih** [comment]
Done: https://github.com/mih/datalad-mihextras/releases/tag/0.7.1
